---
# tasks file for k8s-worker
- name: join + ping
  shell: |
    ping -c 10 192.168.56.15
    kubeadm join --token $(head -1 /vagrant/token) --discovery-token-unsafe-skip-ca-verification 192.168.56.15:6443